/* Mastara menu data — shared by index.html (3D menu) and qr.html (table tents).
   Source: mastararestaurants.com/menu (captured Sep 2026).

   !! PRICES BELOW ARE PLACEHOLDERS !!  The public menu lists no prices, so these are
   plausible Islamabad rooftop figures put in so the ordering flow works end to end.
   REPLACE EVERY `price` WITH MASTARA'S REAL MENU PRICE BEFORE THIS GOES ON A TABLE.
   Numbers are whole rupees, no separators. A price of 0 hides the price and the
   Add button for that dish.

   img   -> img/<img>-560.webp and img/<img>-1200.webp
   model -> models/<model>.glb   (photo-mapped plate; swap for a real scan anytime)
   badges: popular | spicy | veg | chefs                                            */

const CATEGORIES = [
  { id: "desi",        label: "Desi",        tagline: "Authentic Pakistani flavours" },
  { id: "thai",        label: "Thai",        tagline: "Spicy Thai delights" },
  { id: "chinese",     label: "Chinese",     tagline: "Classic Chinese specialties" },
  { id: "fastfood",    label: "Fast Food",   tagline: "Tempting favourites" },
  { id: "continental", label: "Continental", tagline: "Elegant western cuisine" },
];

const BADGES = {
  popular: { label: "Popular",        mark: "★" },
  spicy:   { label: "Spicy",          mark: "◆" },
  veg:     { label: "Vegetarian",     mark: "V" },
  chefs:   { label: "Chef's Special", mark: "✦" },
};

const MENU = [
  // ---------------------------------------------------------------- Desi
  { slug: "chicken-biryani", cat: "desi", name: "Chicken Biryani", price: 1200,
    desc: "Aromatic basmati rice layered with spiced chicken, saffron & fried onions",
    badges: ["popular"], img: "chicken-biryani", model: "chicken-biryani" },
  { slug: "mutton-karahi", cat: "desi", name: "Mutton Karahi", price: 4200,
    desc: "Tender mutton cooked in traditional karahi with tomatoes, ginger & green chilies",
    badges: ["spicy", "popular"], img: "mutton-karahi", model: "mutton-karahi" },
  { slug: "chicken-karahi", cat: "desi", name: "Chicken Karahi", price: 2400,
    desc: "Fresh chicken in a wok with aromatic spices & tomatoes",
    badges: ["spicy"], img: "chicken-karahi", model: "chicken-karahi" },
  { slug: "beef-nihari", cat: "desi", name: "Beef Nihari", price: 1150,
    desc: "Slow-cooked beef shank in rich, spiced gravy — a specialty",
    badges: ["popular", "chefs"], img: "beef-nihari", model: "beef-nihari" },
  { slug: "seekh-kebab", cat: "desi", name: "Seekh Kebab", price: 950,
    desc: "Minced beef kebabs grilled on skewers with traditional spices",
    badges: [], img: "seekh-kebab", model: "seekh-kebab" },
  { slug: "haleem", cat: "desi", name: "Haleem", price: 900,
    desc: "Slow-cooked wheat & meat stew garnished with ginger & fried onions",
    badges: ["popular"], img: "haleem", model: "haleem" },
  { slug: "dal-makhani", cat: "desi", name: "Dal Makhani", price: 950,
    desc: "Black lentils slow-cooked overnight with butter & cream",
    badges: ["veg"], img: "dal-makhani", model: "dal-makhani" },
  { slug: "chicken-tikka", cat: "desi", name: "Chicken Tikka", price: 700,
    desc: "Boneless chicken marinated in yogurt & spices, grilled to perfection",
    badges: ["popular"], img: "chicken-tikka", model: "chicken-tikka" },
  { slug: "mutton-pulao", cat: "desi", name: "Mutton Pulao", price: 1650,
    desc: "Fragrant rice cooked with tender mutton & whole spices",
    badges: [], img: "mutton-pulao", model: "mutton-pulao" },

  // ---------------------------------------------------------------- Thai
  { slug: "pad-thai", cat: "thai", name: "Pad Thai", price: 1600,
    desc: "Stir-fried rice noodles with shrimp, peanuts & tamarind sauce",
    badges: ["popular"], img: "thai", model: "thai" },
  { slug: "green-curry-chicken", cat: "thai", name: "Green Curry Chicken", price: 1750,
    desc: "Creamy coconut curry with Thai basil & fresh vegetables",
    badges: ["spicy", "chefs"], img: "thai", model: "thai" },
  { slug: "tom-yum-soup", cat: "thai", name: "Tom Yum Soup", price: 1150,
    desc: "Hot & sour soup with shrimp, mushrooms & lemongrass",
    badges: ["spicy", "popular"], img: "thai", model: "thai" },
  { slug: "thai-red-curry", cat: "thai", name: "Thai Red Curry", price: 1750,
    desc: "Rich red curry paste with chicken & bamboo shoots",
    badges: ["spicy"], img: "thai", model: "thai" },
  { slug: "thai-fried-rice", cat: "thai", name: "Thai Fried Rice", price: 1250,
    desc: "Jasmine rice wok-fried with egg, vegetables & Thai spices",
    badges: [], img: "thai", model: "thai" },
  { slug: "spring-rolls-thai", cat: "thai", name: "Spring Rolls Thai", price: 850,
    desc: "Crispy rolls with vegetables served with sweet chili sauce",
    badges: ["veg"], img: "thai", model: "thai" },
  { slug: "massaman-curry", cat: "thai", name: "Massaman Curry", price: 1850,
    desc: "Mild aromatic curry with potatoes, peanuts & tender beef",
    badges: ["chefs"], img: "thai", model: "thai" },
  { slug: "thai-basil-chicken", cat: "thai", name: "Thai Basil Chicken", price: 1650,
    desc: "Stir-fried chicken with holy basil & chilies",
    badges: ["spicy", "popular"], img: "thai", model: "thai" },

  // ---------------------------------------------------------------- Chinese
  { slug: "chicken-manchurian", cat: "chinese", name: "Chicken Manchurian", price: 1500,
    desc: "Crispy chicken in tangy, sweet & spicy Manchurian sauce",
    badges: ["popular"], img: "chinese", model: "chinese" },
  { slug: "beef-chilli-dry", cat: "chinese", name: "Beef Chilli Dry", price: 1850,
    desc: "Tender beef strips stir-fried with peppers & green chilies",
    badges: ["spicy", "popular"], img: "chinese", model: "chinese" },
  { slug: "chicken-fried-rice", cat: "chinese", name: "Chicken Fried Rice", price: 1150,
    desc: "Wok-fried rice with chicken, eggs & fresh vegetables",
    badges: [], img: "chinese", model: "chinese" },
  { slug: "chicken-chow-mein", cat: "chinese", name: "Chicken Chow Mein", price: 1300,
    desc: "Stir-fried noodles with chicken & colorful vegetables",
    badges: ["popular"], img: "chinese", model: "chinese" },
  { slug: "hot-sour-soup", cat: "chinese", name: "Hot & Sour Soup", price: 900,
    desc: "Tangy soup with chicken, mushrooms & tofu",
    badges: ["spicy"], img: "chinese", model: "chinese" },
  { slug: "dragon-chicken", cat: "chinese", name: "Dragon Chicken", price: 1700,
    desc: "Crispy chicken in fiery dragon sauce with sesame seeds",
    badges: ["spicy", "chefs"], img: "chinese", model: "chinese" },
  { slug: "spring-rolls", cat: "chinese", name: "Spring Rolls", price: 850,
    desc: "Crispy rolls stuffed with vegetables & chicken",
    badges: ["popular"], img: "chinese", model: "chinese" },
  { slug: "szechuan-chicken", cat: "chinese", name: "Szechuan Chicken", price: 1600,
    desc: "Spicy Szechuan style chicken with dried chilies",
    badges: ["spicy"], img: "chinese", model: "chinese" },

  // ---------------------------------------------------------------- Fast Food
  { slug: "classic-burger", cat: "fastfood", name: "Classic Burger", price: 1150,
    desc: "Juicy beef patty with lettuce, tomato & special sauce",
    badges: ["popular"], img: "fastfood", model: "fastfood" },
  { slug: "chicken-zinger", cat: "fastfood", name: "Chicken Zinger", price: 950,
    desc: "Crispy fried chicken fillet with coleslaw & mayo",
    badges: ["popular"], img: "fastfood", model: "fastfood" },
  { slug: "loaded-fries", cat: "fastfood", name: "Loaded Fries", price: 750,
    desc: "Crispy fries topped with cheese, jalapeños & sour cream",
    badges: ["veg"], img: "fastfood", model: "fastfood" },
  { slug: "chicken-wings", cat: "fastfood", name: "Chicken Wings", price: 1050,
    desc: "Crispy wings with choice of BBQ, buffalo or honey garlic",
    badges: ["popular"], img: "fastfood", model: "fastfood" },
  { slug: "club-sandwich", cat: "fastfood", name: "Club Sandwich", price: 1050,
    desc: "Triple-decker with chicken, egg, bacon & veggies",
    badges: [], img: "fastfood", model: "fastfood" },
  { slug: "pizza-margherita", cat: "fastfood", name: "Pizza Margherita", price: 1400,
    desc: "Classic pizza with mozzarella, tomato & fresh basil",
    badges: ["veg"], img: "fastfood", model: "fastfood" },
  { slug: "bbq-chicken-pizza", cat: "fastfood", name: "BBQ Chicken Pizza", price: 1700,
    desc: "Smoky BBQ sauce with grilled chicken & onions",
    badges: ["popular"], img: "fastfood", model: "fastfood" },
  { slug: "cheese-sticks", cat: "fastfood", name: "Cheese Sticks", price: 800,
    desc: "Golden fried mozzarella sticks with marinara",
    badges: ["veg"], img: "fastfood", model: "fastfood" },

  // ---------------------------------------------------------------- Continental
  { slug: "grilled-chicken-steak", cat: "continental", name: "Grilled Chicken Steak", price: 2200,
    desc: "Juicy chicken breast with mushroom sauce & mashed potatoes",
    badges: ["popular"], img: "continental", model: "continental" },
  { slug: "beef-steak", cat: "continental", name: "Beef Steak", price: 3300,
    desc: "Tender beef steak with pepper sauce & seasonal vegetables",
    badges: ["popular", "chefs"], img: "continental", model: "continental" },
  { slug: "chicken-pasta", cat: "continental", name: "Chicken Pasta", price: 1600,
    desc: "Penne in creamy white sauce with grilled chicken & herbs",
    badges: ["popular"], img: "continental", model: "continental" },
  { slug: "mushroom-pasta", cat: "continental", name: "Mushroom Pasta", price: 1400,
    desc: "Spaghetti with sautéed mushrooms in garlic cream sauce",
    badges: ["veg"], img: "continental", model: "continental" },
  { slug: "grilled-salmon", cat: "continental", name: "Grilled Salmon", price: 3800,
    desc: "Fresh salmon fillet with lemon butter & asparagus",
    badges: ["chefs"], img: "continental", model: "continental" },
  { slug: "caesar-salad", cat: "continental", name: "Caesar Salad", price: 1200,
    desc: "Romaine lettuce with Caesar dressing, croutons & parmesan",
    badges: ["veg"], img: "continental", model: "continental" },
  { slug: "lamb-chops", cat: "continental", name: "Lamb Chops", price: 3600,
    desc: "Grilled lamb chops with rosemary & mint sauce",
    badges: ["chefs"], img: "continental", model: "continental" },
  { slug: "chicken-cordon-bleu", cat: "continental", name: "Chicken Cordon Bleu", price: 2400,
    desc: "Stuffed chicken breast with ham & Swiss cheese",
    badges: ["popular"], img: "continental", model: "continental" },
];

const VENUE = {
  name: "Mastara",
  tagline: "Bite & Bubbles",
  blurb: "Rooftop dining above the Islamabad skyline",
  address: "6th Floor Rooftop, Galleria Mall, I-8 Markaz, Islamabad",
  phone: "+92 336 8556644",
  whatsapp: "923368556644",
  hours: "Mon–Thu 12 PM – 12 AM · Fri–Sun 12 PM – 1 AM",
  site: "https://www.mastararestaurants.com",
  instagram: "https://www.instagram.com/mastaraislamabad",
};
